# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VoteMenu(object):
    def setupUi(self, VoteMenu):
        VoteMenu.setObjectName("VoteMenu")
        VoteMenu.resize(450, 450)
        VoteMenu.setMinimumSize(QtCore.QSize(450, 450))
        VoteMenu.setMaximumSize(QtCore.QSize(450, 450))
        font = QtGui.QFont()
        font.setPointSize(8)
        VoteMenu.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=VoteMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.vote_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.vote_title.setGeometry(QtCore.QRect(50, 10, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.vote_title.setFont(font)
        self.vote_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vote_title.setObjectName("vote_title")
        self.vote_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vote_button.setGeometry(QtCore.QRect(100, 240, 75, 34))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.vote_button.setFont(font)
        self.vote_button.setObjectName("vote_button")
        self.vote_john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.vote_john.setGeometry(QtCore.QRect(100, 160, 67, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.vote_john.setFont(font)
        self.vote_john.setObjectName("vote_john")
        self.vote_jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.vote_jane.setGeometry(QtCore.QRect(240, 160, 66, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.vote_jane.setFont(font)
        self.vote_jane.setObjectName("vote_jane")
        self.intro_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.intro_label.setGeometry(QtCore.QRect(60, 70, 321, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.intro_label.setFont(font)
        self.intro_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.intro_label.setWordWrap(True)
        self.intro_label.setObjectName("intro_label")
        self.exit_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.exit_label.setGeometry(QtCore.QRect(40, 290, 371, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exit_label.setFont(font)
        self.exit_label.setText("")
        self.exit_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exit_label.setWordWrap(True)
        self.exit_label.setObjectName("exit_label")
        self.exit_button_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button_2.setGeometry(QtCore.QRect(240, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.exit_button_2.setFont(font)
        self.exit_button_2.setObjectName("exit_button_2")
        VoteMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=VoteMenu)
        self.statusbar.setObjectName("statusbar")
        VoteMenu.setStatusBar(self.statusbar)

        self.retranslateUi(VoteMenu)
        QtCore.QMetaObject.connectSlotsByName(VoteMenu)

    def retranslateUi(self, VoteMenu):
        _translate = QtCore.QCoreApplication.translate
        VoteMenu.setWindowTitle(_translate("VoteMenu", "MainWindow"))
        self.vote_title.setText(_translate("VoteMenu", "Vote Menu"))
        self.vote_button.setText(_translate("VoteMenu", "Vote"))
        self.vote_john.setText(_translate("VoteMenu", "John"))
        self.vote_jane.setText(_translate("VoteMenu", "Jane"))
        self.intro_label.setText(_translate("VoteMenu", "Hello! Please select a candidate and press \'Vote\' to submit"))
        self.exit_button_2.setText(_translate("VoteMenu", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoteMenu = QtWidgets.QMainWindow()
    ui = Ui_VoteMenu()
    ui.setupUi(VoteMenu)
    VoteMenu.show()
    sys.exit(app.exec())
